---
controller_execution_environments:
  - name: "ee-casc"
    image: "quay.io/automationiberia/aap/ee-casc:latest"
    pull: always
    credential: "{{ orgs }} {{ env }} Automation Private Hub Container Registry"
...
